name: goldblatt2020
channels:
  - conda-forge
  - defaults
dependencies:
  - basemap=1.2.2
  - climt=0.9.1
  - hdf4=4.2.13
  - hdf5=1.10.4
  - matplotlib=3.3.2
  - matplotlib-base=3.3.2
  - netcdf4=1.5.3
  - numpy=1.19.2
  - pandas=0.21.0
  - proj=7.2.0
  - python=3.6.12
  - python-dateutil=2.8.1
  - python_abi=3.6
  - scipy=1.2.1
