name: goldblatt2020
channels:
  - conda-forge
  - defaults
dependencies:
  - astroid=2.4.2
  - basemap=1.2.2
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2020.11.8
  - certifi=2020.11.8
  - cftime=1.2.1
  - climt=0.9.1
  - curl=7.71.1
  - cycler=0.10.0
  - freetype=2.10.4
  - geos=3.8.1
  - hdf4=4.2.13
  - hdf5=1.10.4
  - intel-openmp=2019.4
  - isort=5.6.4
  - jpeg=9b
  - kiwisolver=1.3.0
  - krb5=1.18.2
  - lazy-object-proxy=1.4.3
  - lcms2=2.11
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.71.1
  - libcxx=11.0.0
  - libedit=3.1.20191231
  - libffi=3.3
  - libgfortran=3.0.1
  - liblapack=3.8.0
  - libnetcdf=4.7.3
  - libpng=1.6.37
  - libssh2=1.9.0
  - libtiff=4.1.0
  - lz4-c=1.9.2
  - matplotlib=3.3.2
  - matplotlib-base=3.3.2
  - mccabe=0.6.1
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - ncurses=6.2
  - netcdf4=1.5.3
  - numpy=1.19.2
  - numpy-base=1.19.2
  - olefile=0.46
  - openssl=1.1.1h
  - pandas=0.21.0
  - pillow=8.0.1
  - pip=20.2.4
  - proj=7.2.0
  - pylint=2.6.0
  - pyparsing=2.4.7
  - pyproj=3.0.0.post1
  - pyshp=2.1.2
  - python=3.6.12
  - python-dateutil=2.8.1
  - python_abi=3.6
  - readline=8.0
  - scipy=1.2.1
  - setuptools=50.3.1
  - six=1.15.0
  - sqlite=3.33.0
  - tk=8.6.10
  - toml=0.10.1
  - tornado=6.0.4
  - typed-ast=1.4.1
  - wheel=0.35.1
  - wrapt=1.11.2
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.5